-- DROP TABLE IF EXISTS blogful_articles;
CREATE TABLE blogful_articles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL, /* TIMESTAMPTZ shorthand for TIMESTAMP WITH TIME ZONE; forces all timestamp entries to be recorded in UTC time */
    content TEXT
);